apply plugin: 'com.android.application'

android {
    namespace 'com.iljal.grblcontoller'
    compileSdk 36

    defaultConfig {
        applicationId "com.iljal.grblcontoller"
        minSdk 23
        targetSdk 36
        versionCode 40
        versionName "2.59"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
    }

    buildFeatures {
        dataBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.10'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:23.1.1'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.3.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation 'androidx.appcompat:appcompat:1.6.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'org.greenrobot:eventbus:3.3.1'
    implementation 'com.github.warkiz:IndicatorSeekBar:v2.1.1'
    implementation 'com.github.felHR85:UsbSerial:6.1.0'
    implementation 'com.github.nbsp-team:MaterialFilePicker:384d8538b0'
    implementation 'com.github.satyan:sugar:v1.5'
    implementation 'com.github.GrenderG:Toasty:1.5.2'

    testImplementation 'junit:junit:4.13.2'
}

apply plugin: 'com.google.gms.google-services'
